# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    # Setup Node.js version for the matrix
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Install dependencies, build, and test for react-frontend
    - name: cd into react-frontend
      run: cd react-frontend
      working-directory: ./TODO_LIST
    - name: Install CI for react-frontend
      run: npm ci
      working-directory: ./react-frontend
    - name: Build react-frontend
      run: npm run build
      working-directory: ./react-frontend
    - name: Test react-frontend
      run: npm test
      working-directory: ./react-frontend
    
    # Install dependencies, build, and test for express-backend
    - name: cd into express-backend
      run: cd express-backend
      working-directory: ./TODO_LIST
    - name: Install dependencies for express-backend
      run: npm ci
      working-directory: ./express-backend
    - name: Build express-backend
      run: npm run build --if-present
      working-directory: ./express-backend
    - name: Test express-backend
      run: npm test
      working-directory: ./express-backend
